services:
  app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: ghcr.io/${OWNER_REPO}/finance-app:${IMAGE_TAG}
    container_name: finance-management-front
    ports:
      - "3000:3000"
    environment:
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - AI_GATEWAY_API_KEY=${AI_GATEWAY_API_KEY}
    restart: unless-stopped
    networks:
      - public_network

networks:
  public_network:
    external: true

