services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: lucasdias067/my-private-repository:${IMAGE_TAG:-latest}
    container_name: finance-management-front
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://host.docker.internal:3334}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-jwt}
      - AI_GATEWAY_API_KEY=${AI_GATEWAY_API_KEY}
      - NEXT_PUBLIC_AVATAR_URL=${NEXT_PUBLIC_AVATAR_URL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - public_network

networks:
  public_network:
    external: true

